SPECIAL_CASES = {
    "Rhino Tank": "rhino",
    "Dashound": "coach",
    "Declasse Vigero ZX": "vigero2",
    "Obey Omnis e-GT": "omnisegt",
    "Albany Cavalcade XL": "cavalcade3",
    "Vapid Dominator FX": "dominator10",
    "Vapid Firebolt ASP" : "firebolt",
    "Pfister 811" : "pfister811",
    "Truffade Z-Type" : "ztype",
    "Maibatsu Penumbra FF": "penumbra2",
    "MTL Fire Truck": "firetruk",
    "Mammoth Patriot Mil-Spec": "patriot3",
    "Declasse Tampa GT": "tampa4",
    "Grotti Stinger TT": "stingertt",
    "Übermacht Sentinel Classic": "sentinel3",
    "Dinka Veto Modern" : "veto2",
    "Declasse Hotring Sabre": "hotring",
    "Brute Bobcat Security Stockade": "stockade4",
    "Pegassi Pizza Boy" : "pizzaboy",
    "Bravado Buffalo EVX": "buffalo5",
    "Pfister Comet Safari": "comet4",
    "Vapid Caracara 4x4" : "caracara2",
    "Declasse Tulip M-100" : "tulip2",
    "Declasse Tahoma Coupe": "tahoma",
    "Jobuilt Velum 5-Seater" : "velum2",
    "Declasse Yosemite 1500" : "yosemite1500",
    "Grotti Cheetah Classic" : "cheetah2",
    "Nagasaki Buzzard Attack Chopper" : "buzzard",
    "JoBuilt Phantom Custom" : "phantom3",
    "Pfister Comet S2 Cabrio" : "comet7",
    "Enus Paragon R": "paragon",
    "Vapid Dominator GTT": "dominator8",
    "BF Ramp Buggy": "dune4",
    "Bravado Hotring Hellfire": "gauntlet6",
    "Dinka Veto Classic": "veto",
    "Ocelot R88": "formula2",
    "Karin Sultan Classic": "sultan2",
    "Dinka Kanjo SJ": "kanjo",
    "Pfister Astron Custom": "astron2",
    "Vapid Clique Wagon": "clique2",
    "Enus Windsor Drop": "windsor2",
    "Benefactor Schlagen GT" : "schlagen",
    "Annis S80RR" : "s80",
    "Enus Paragon S" : "paragon3",
    "Överflöd Entity MT" : "entity3",
    "Weeny Issi Rally" : "issi8",
    "Jobuilt Phantom Wedge" : "phantom2",
    "Nagasaki Blazer Aqua" : "blazer5",
    "Karin Everon RS" : "everon3",
    "Übermacht Rebla GTS" : "rebla",
    "Western Police Bike" : "policeb",
    "Invetero Coquette D10 Pursuit" : "polcoquette4",
    "Vapid Dominator FX Interceptor" : "poldominator10",
    "Declasse Impaler LX Cruiser" : "polimpaler6",
    "Declasse Impaler SZ Cruiser" : "polimpaler5",
    "Vapid Stanier LE Cruiser" : "police5",
    "Vapid Unmarked Cruiser" : "police4",
    "Declasse Park Ranger" : "pranger",
    "Albany V–STR" : "vstr",
    "Western Company Duster 300–H" : "duster2",
    "Lampadati Tropos Rallye" : "tropos",
    "Vapid Caracara Pursuit" : "polcaracara",
    "Canis Terminus Patrol" : "polterminus",
    "Willard Outreach Faction" : "polfaction2",
    "Bravado Greenwood Cruiser" : "polgreenwood",
    "Bravado Dorado Cruiser" : "poldorado",
    "Bravado Gauntlet Interceptor" : "polgauntlet",
}